#!/usr/bin/env python3
"""
Generate CI/CD test summary for GitHub Actions.
Outputs results to both console and GitHub Step Summary.
"""

import os
import sys


def log_both(message, summary_file=None):
    """Output message to both console and GitHub Step Summary"""
    print(message)
    if summary_file:
        summary_file.write(message + "\n")


def get_job_status_emoji(result):
    """Get emoji and formatting for job result"""
    if result == "success":
        return "✅", "**PASSED**"
    if result == "failure":
        return "❌", "**FAILED**"
    return "⚠️", f"**{result.upper()}**"


def generate_summary():
    """Generate comprehensive test summary"""
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")

    # Job results from environment variables
    jobs = {
        "pre-commit": os.environ.get("PRE_COMMIT_RESULT", "unknown"),
        "security-scan": os.environ.get("SECURITY_SCAN_RESULT", "unknown"),
        "ansible-syntax": os.environ.get("ANSIBLE_SYNTAX_RESULT", "unknown"),
        "docs-validation": os.environ.get("DOCS_VALIDATION_RESULT", "unknown"),
    }

    # Critical jobs that must pass
    critical_jobs = ["pre-commit", "ansible-syntax"]

    if summary_path:
        try:
            with open(summary_path, "a", encoding="utf-8") as summary_file:
                _write_summary(jobs, critical_jobs, summary_file)
        except OSError as e:
            print(f"Warning: Could not open summary file: {e}")
            _write_summary(jobs, critical_jobs, None)
    else:
        _write_summary(jobs, critical_jobs, None)

    critical_passed = all(jobs[job] == "success" for job in critical_jobs)
    return 0 if critical_passed else 1


def _write_summary(jobs, critical_jobs, summary_file):
    """Write the actual summary content"""
    log_both("# 🚀 NeoSetup CI/CD Test Summary", summary_file)
    log_both("", summary_file)

    # Pre-commit (covers all linting)
    log_both("## 🔍 Pre-commit Checks", summary_file)
    log_both("", summary_file)
    log_both("Runs all 20 hooks: yamllint, ansible-lint, black, flake8, pylint,", summary_file)
    log_both("bandit, safety, shellcheck, markdownlint, detect-secrets, and more.", summary_file)
    log_both("", summary_file)
    emoji, status = get_job_status_emoji(jobs["pre-commit"])
    log_both(f"{emoji} pre-commit: {status}", summary_file)
    log_both("", summary_file)

    # Ansible multi-version
    log_both("## 🎭 Ansible Compatibility", summary_file)
    log_both("", summary_file)
    log_both("Tests syntax with Ansible 6.0 and 7.0.", summary_file)
    log_both("", summary_file)
    emoji, status = get_job_status_emoji(jobs["ansible-syntax"])
    log_both(f"{emoji} ansible-syntax: {status}", summary_file)
    log_both("", summary_file)

    # Security
    log_both("## 🛡️ Security Scanning", summary_file)
    log_both("", summary_file)
    log_both("CodeQL and Trivy vulnerability scanning.", summary_file)
    log_both("", summary_file)
    emoji, status = get_job_status_emoji(jobs["security-scan"])
    log_both(f"{emoji} security-scan: {status}", summary_file)
    log_both("", summary_file)

    # Docs
    log_both("## 📚 Documentation", summary_file)
    log_both("", summary_file)
    log_both("Validates documentation completeness and checks markdown links.", summary_file)
    log_both("", summary_file)
    emoji, status = get_job_status_emoji(jobs["docs-validation"])
    log_both(f"{emoji} docs-validation: {status}", summary_file)
    log_both("", summary_file)

    # Overall status
    critical_passed = all(jobs[job] == "success" for job in critical_jobs)

    if critical_passed:
        log_both("## 🎉 Overall Status: SUCCESS", summary_file)
        log_both("", summary_file)
        log_both("🚀 **All critical tests passed! NeoSetup is ready to rock!**", summary_file)
    else:
        failed_critical = [job for job in critical_jobs if jobs[job] != "success"]
        log_both("## ⚠️ Overall Status: CRITICAL ISSUES", summary_file)
        log_both("", summary_file)
        log_both(f"❌ Critical jobs failed: {', '.join(failed_critical)}", summary_file)
        log_both("🔧 **Action Required**: Fix critical issues before deployment", summary_file)

    log_both("", summary_file)
    log_both("---", summary_file)
    log_both("*Generated by NeoSetup CI/CD Pipeline*", summary_file)


def main():
    """Main entry point"""
    sys.exit(generate_summary())


if __name__ == "__main__":
    main()
