# NeoSetup Project Standard: 120 character line length
[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'
extend-exclude = '''
# Exclude files or directories
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 120
extend-ignore = []
exclude = [
    ".git",
    "__pycache__",
    "dist",
    "build",
    "*.egg-info",
]

[tool.pylint]
[tool.pylint.format]
max-line-length = 120

[tool.pylint.main]
fail-under = 10.0

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.bandit]
# Bandit configuration for security scanning
exclude_dirs = [".git", ".venv", "__pycache__", "dist", "build"]
skips = []  # Don't skip any tests by default - use targeted nosec comments instead
