---
galaxy_info:
  author: NeoSetup Team
  description: Docker installation and configuration
  company: NeoSetup

  license: MIT

  min_ansible_version: '2.9'

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - docker
    - containers
    - development

dependencies: [ ]
