---
# Common role metadata

galaxy_info:
  author: NeoSetup Team
  description: Common tasks and setup for all NeoSetup operators
  company: NeoSetup
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Fedora
      versions:
        - '37'
        - '38'
    - name: Darwin
      versions:
        - all
  galaxy_tags:
    - neosetup
    - development
    - configuration
    - matrix

dependencies: [ ]
