---
galaxy_info:
  author: NeoSetup Team
  description: Matrix-themed tmux configuration with operator inheritance
  company: NeoSetup

  license: MIT

  min_ansible_version: '2.9'

  platforms:
    - name: macOS
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - tmux
    - terminal
    - multiplexer
    - matrix
    - development

dependencies: [ ]
