---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

  vars:
    # Default operator - can be overridden via command line
    neosetup_operator: "jiveturkey"

    # User configuration
    neosetup_user: "{{ ansible_user }}"
    neosetup_home: "{{ ansible_env.HOME }}"

    # Enable features
    neosetup_backup_configs: true
    neosetup_install_packages: true
    neosetup_configure_shell: true
    neosetup_configure_tmux: true
    neosetup_install_docker: true
    neosetup_set_default_shell: true
